### ISSUE TITLE
BSP u-boot 不会在启动时输出 log

### ISSUE THREAD

**Issue by chainsx** [edk2-porting/edk2-rk3399#2]
如题，
强行更改 BSP u-boot 分辨率后 ，在 hdmi 还是不会有输出。
mainline u-boot 试过很多版本，将此作为内核启动会失败。

**Comment by evi0s** [comment]
Yes, I did try mainline u-boot and it's indeed has no HDMI output. I made this working on a vendor version of u-boot w/ Rockchip DRM driver ships with my Orange Pi 4B (exact `Rockchip DRM driver' while configuring u-boot). Sadly I'm no longer having this board so sorry that I could not figure this out at this time and provide more info to you, but I suggest that you may try a vendor version u-boot (which shows a big logo on my Orange Pi 4B while u-boot booting) rather than the mainline.
